# Generated by Django 3.2.4 on 2021-06-29 08:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Favorites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='owner',
            new_name='author',
        ),
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together={('author', 'product')},
        ),
    ]
