# Generated by Django 3.2.4 on 2021-06-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Favorites', '0002_auto_20210629_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'favorites', 'verbose_name_plural': 'favorites'},
        ),
    ]
