# Generated by Django 3.2.4 on 2021-06-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default=False, max_length=300),
        ),
    ]
