# Generated by Django 3.2.4 on 2021-06-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
