# Generated by Django 3.2.4 on 2021-06-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_product_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='like',
        ),
    ]
